version: '2'
services:
  wordpress:
    image: wp-wordpress:latest
    ports:
     - "80:80"
     - "443:443"
    links:
     - wordpress_db:mysql
    #volumes:
    # - $HOME/docker-data/nginx-www:/usr/share/nginx/www:rw
    # - $HOME/docker-data/nginx-cache:/var/cache/nginx:rw
    env_file:
     - ./env/wordpress.env
    cpu_shares: 40
    mem_limit: 400M
  wordpress_db:
    image: mariadb:5.5.48
    #volumes:
    # - $HOME/docker-data/mysql-data:/var/lib/mysql:rw
    env_file:
     - ./env/mysql.env
    cpu_shares: 40
    mem_limit: 400M
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links:
     - wordpress_db:mysql
    environment:
    # - PMA_ARBITRARY=1
     - PMA_HOST=mysql
    restart: always
    ports:
     - 8080:80
    cpu_shares: 10
    mem_limit: 50M

